USE [master]
GO
CREATE DATABASE [HtmlHelperDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HtmlHelperDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\HtmlHelperDb.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HtmlHelperDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\HtmlHelperDb_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [HtmlHelperDb] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HtmlHelperDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HtmlHelperDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [HtmlHelperDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HtmlHelperDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HtmlHelperDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [HtmlHelperDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HtmlHelperDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [HtmlHelperDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HtmlHelperDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [HtmlHelperDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [HtmlHelperDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [HtmlHelperDb]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Usuario](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Email] [varchar](80) NOT NULL,
	[Contra] [varchar](80) NOT NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)


GO
SET ANSI_PADDING OFF
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Genero](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Genero] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)

GO
SET ANSI_PADDING OFF
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Hobby](
	[Id] [int] IDENTITY(1,1) NOT NULL,
    [Descripcion] [Varchar](50) NOT NULL,
    [Cotejado] [BIT] NULL,
CONSTRAINT [PK_Hobby] PRIMARY KEY CLUSTERED
(
    [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)

CREATE TABLE [dbo].[Persona](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Cedula] [Varchar](15) NOT NULL,
	[Nombre] [Varchar](50) NOT NULL,
	[Apellido] [Varchar](50) NOT NULL,
	[Edad] [INT] NOT NULL,
    [Telefono] [Varchar](13) NOT NULL,
    [Email] [Varchar](50) NOT NULL,
    [GeneroId] [Int] NULL,
    [EstadoCivil] [Varchar](80) NULL,
    [Hobbys] [Varchar](max) NULL,
CONSTRAINT [PK_Persona] PRIMARY KEY CLUSTERED
(
    [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)

ALTER TABLE [dbo].[Persona]  WITH CHECK ADD  CONSTRAINT [FK_Persona_Genero] FOREIGN KEY([GeneroId])
REFERENCES [dbo].[Genero] ([Id])

ALTER TABLE [dbo].[Persona] CHECK CONSTRAINT [FK_Persona_Genero]


GO
USE [HtmlHelperDb]

INSERT INTO [dbo].Genero VALUES('Masculino')
INSERT INTO [dbo].Genero VALUES('Femenino')